// Import the Next.js response helper class
import { NextResponse } from "next/server";
// Import the SAP scraper helper function
import { fetchSapLessonContent } from "../../../lib/sap-helpers";

// Helper function to query Gemini API via standard HTTP POST request
async function queryGemini(api_key, model, prompt_text, user_prompt_details) {
  // Initialize thinking level variable
  let thinking_level = null;
  // Initialize target model identifier with base model name
  let target_model = model;
  // Check if model string contains the custom thinking configurations delimiter
  if (model.includes("|")) {
    // Split the model name and thinking configurations
    const parts = model.split("|");
    // Assign base model name
    target_model = parts[0];
    // Assign thinking level parameter
    thinking_level = parts[1];
  // Close model string check block
  }
  // Construct the Google generative language API endpoint URL
  const api_url = `https://generativelanguage.googleapis.com/v1beta/models/${target_model}:generateContent?key=${api_key}`;
  // Define target JSON structure schema for questions generated by Gemini
  const schema = {
    // Specify target root JSON type is object
    type: "OBJECT",
    // Define properties of the root object
    properties: {
      // Questions array schema
      questions: {
        // Declare questions field as an array
        type: "ARRAY",
        // Define items schema for questions array
        items: {
          // Declare individual item type as object
          type: "OBJECT",
          // Define properties of question item object
          properties: {
            // Title question string
            question: { type: "STRING" },
            // Multiple-choice options array
            options: {
              // Declare options as array type
              type: "ARRAY",
              // Specify options array items as string elements
              items: { type: "STRING" }
            // Close options schema properties
            },
            // Correct option text matching one in options
            correct_answer: { type: "STRING" },
            // Detailed explanation of the correct selection
            explanation: { type: "STRING" }
          // Close properties definitions
          },
          // Require all properties to be present in output
          required: ["question", "options", "correct_answer", "explanation"]
        // Close array items schema definition
        }
      // Close questions field schema definition
      }
    // Close root properties dictionary
    },
    // Enforce questions array presence in output JSON
    required: ["questions"]
  // Close schema dictionary
  };
  // Construct parameters payload for the generative model API request
  const payload = {
    // Define input contents parts list
    contents: [{
      // Embed instruction details and context contents
      parts: [{ text: `${user_prompt_details}\n\nContent:\n${prompt_text}` }]
    // Close contents array element
    }],
    // Setup model configuration options
    generationConfig: {
      // Set response format to application/json
      responseMimeType: "application/json",
      // Supply schema definition for verification
      responseSchema: schema
    // Close generationConfig dictionary
    }
  // Close payload dictionary
  };
  // Check if model thinking configuration is set
  if (thinking_level) {
    // Inject thinkingConfig settings to configuration parameters
    payload.generationConfig.thinkingConfig = { thinkingLevel: thinking_level };
  // Close thinking level check block
  }
  // Send POST request querying the generative model API
  const response = await fetch(api_url, {
    // Specify POST method
    method: "POST",
    // Pass headers
    headers: {
      // Specify JSON content type
      "Content-Type": "application/json"
    // Close headers dictionary
    },
    // Stringify and pass JSON payload body
    body: JSON.stringify(payload)
  // Close fetch request configuration
  });
  // Check if response is not successful
  if (!response.ok) {
    // Read raw error text content from response
    const errorText = await response.text();
    // Set placeholder readable message text
    let readableMsg = errorText;
    // Attempt to extract structured error details from JSON response
    try {
      // Parse error response text as JSON
      const errorJson = JSON.parse(errorText);
      // Extract Google API error message string
      readableMsg = errorJson.error?.message || errorText;
    // Catch JSON parsing failures
    } catch (e) {
      // No operation
    }
    // Throw API failure error detailing status code and response messages
    throw new Error(`Gemini API HTTP Error ${response.status}: ${readableMsg}`);
  // Close response success check block
  }
  // Parse response body as JSON
  const resp_data = await response.json();
  // Navigate structure to retrieve response text from parts
  const text_response = resp_data.candidates?.[0]?.content?.parts?.[0]?.text;
  // Verify if returned text response content is empty
  if (!text_response) {
    // Throw empty response exception
    throw new Error("Empty response from Gemini API.");
  // Close validation check block
  }
  // Parse response string into a JS object and return it
  return JSON.parse(text_response);
// Close queryGemini helper function block
}

// Helper function to randomly shuffle an array
function shuffle(array) {
  // Loop through array elements in reverse order
  for (let i = array.length - 1; i > 0; i--) {
    // Select random index index between 0 and active index
    const j = Math.floor(Math.random() * (i + 1));
    // Swap array elements using destructuring assignment
    [array[i], array[j]] = [array[j], array[i]];
  // Close array reverse loop
  }
  // Return the shuffled array reference
  return array;
// Close shuffle function block
}

// Export the asynchronous POST handler function
export async function POST(request) {
  // Begin the main try block for error handling
  try {
    // Parse the request body parameters as JSON
    const params = await request.json();
    // Retrieve list of raw unit IDs or URLs
    const unit_inputs = params.unit_ids || [];
    // Extract difficulty parameter or default to Intermediate
    const difficulty = params.difficulty || "Intermediate";
    // Extract requested quiz question count or default to 5
    const count = params.count || 5;
    // Resolve SAP session cookie from parameters or server env
    const sap_cookie = (process.env.SAP_SESSION_COOKIE || "").trim();
    // Resolve Gemini API key from parameters or server env
    const gemini_key = (params.gemini_api_key || "").trim() || (process.env.GEMINI_API_KEY || "").trim();
    // Resolve Gemini model version parameter or default to gemini-3.5-flash
    const gemini_model = (params.gemini_model || "gemini-3.5-flash").trim();
    // Validate if Gemini API key is provided
    if (!gemini_key) {
      // Throw missing key exception
      throw new Error("Missing Gemini API Key. Provide it in .env or via UI.");
    // Close key validation block
    }
    // Validate if lesson inputs array has elements
    if (unit_inputs.length === 0) {
      // Throw missing selection exception
      throw new Error("Please provide at least one valid SAP Unit ID or URL.");
    // Close inputs validation block
    }
    // Get total number of selected lessons
    const total_lessons = unit_inputs.length;
    // Calculate base questions count per lesson using integer division
    const base_count = Math.floor(count / total_lessons);
    // Calculate remainder questions to distribute
    const remainder = count % total_lessons;
    // Create base array mapping question distribution counts per lesson
    let lesson_counts = Array(total_lessons).fill(base_count);
    // Loop through remainder count
    for (let r = 0; r < remainder; r++) {
      // Increment lesson count elements circularly
      lesson_counts[r] += 1;
    // Close remainder loop
    }
    // Shuffling question distributions across lessons randomly
    lesson_counts = shuffle(lesson_counts);
    // Initialize array to hold final aggregate quiz questions
    const all_generated_quizzes = [];
    // Loop through each lesson input index
    for (let idx = 0; idx < unit_inputs.length; idx++) {
      // Assign the input item URL/UUID
      const item = unit_inputs[idx];
      // Get count of questions for this lesson
      const lesson_count = lesson_counts[idx];
      // Check if no questions are allocated for this lesson
      if (lesson_count < 1) {
        // Skip generating questions for this lesson
        continue;
      // Close count check block
      }
      // Scrape lesson content using helper scraper
      const lesson_content = await fetchSapLessonContent(item, sap_cookie);
      // Prepare instructions prompt for the Gemini AI model
      const prompt_instructions = (
        // Set goal prompt instructions
        `Generate a multiple-choice quiz based on the provided SAP Learning Journey educational text.\n` +
        // Define exact count parameter
        `Provide exactly ${lesson_count} high-quality certification-style questions.\n` +
        // Define difficulty level parameters
        `Ensure difficulty matches '${difficulty}' level (appropriate depth, wording, and trickiness).\n` +
        // Set choices formatting parameter options count
        `Each question must have exactly 4 options. Make sure options are distinct.\n` +
        // Set correct field details instruction
        `Provide the exact correct option text in the 'correct_answer' field, and explain why it is correct in the 'explanation' field.\n` +
        // Filter UI markup prompt instructions
        `Ignore navigation, UI components, copyright notices, and structural text when creating questions.`
      );
      // Query Gemini API to generate the quiz structure
      const gemini_quiz_dict = await queryGemini(gemini_key, gemini_model, lesson_content.text, prompt_instructions);
      // Extract returned questions array or default to empty list
      const questions_list = gemini_quiz_dict.questions || [];
      // Loop through each generated question item
      for (const quiz_item of questions_list) {
        // Append unit ID metadata to question
        quiz_item.unit_id = lesson_content.unit_id;
        // Append unit title metadata to question
        quiz_item.unit_title = lesson_content.title;
        // Append source URL metadata to question
        quiz_item.source_url = item;
        // Push processed question to final aggregate list
        all_generated_quizzes.push(quiz_item);
      // Close question items loop
      }
    // Close lesson inputs loop
    }
    // Return successful quiz generation response payload
    return NextResponse.json({ success: true, quiz: all_generated_quizzes });
  // Catch any errors raised during processing
  } catch (error) {
    // Return an error JSON response with 500 status code
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  // Close catch block
  }
// Close POST handler block
}
